spring:
  application:
    name: inmobiliaria
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: bWlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY=
  expiration: ${JWT_EXPIRATION_TIME:86400000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION_TIME:2592000000}

cloudinary:
  cloud_name: ${CLOUD_NAME}
  cloud_api_key: ${CLOUD_API_KEY}
  cloud_api_secret: ${CLOUD_API_SECRET}

admin:
  email: ${ADMIN_EMAIL}